name: gaussian_splatting                                                                    
channels:                                                                                   
  - pytorch                                                                                 
  - conda-forge       
  - defaults
  - nvidia
dependencies:
  - cuda-toolkit=12.1
  - plyfile
  - python
  - pip
  - pytorch-cuda=12.1
  - torchmetrics
  - torchvision
  - torchaudio
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
